name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is named master

jobs:
  web-deploy:
    name: Production Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚀 Sync files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "145.223.108.148"
          username: "u149904157"
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: "public_html/"
